# Generated by Django 5.1.6 on 2025-02-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
